[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.dev]
workspace = false
dependencies = ["format-toml"]
run_task = { name = "dev-workspace", fork = true }

[tasks.dev-workspace]
dependencies = ["format", "clippy", "build", "test"]

[tasks.ci]
workspace = false
dependencies = ["print-env-flow", "check-toml"]
run_task = { name = "ci-workspace", fork = true }

[tasks.ci-workspace]
dependencies = ["check-format", "clippy", "build", "test"]

[tasks.check-toml]
condition = { env_set = ["CARGO_MAKE_FORMAT_TOML_FILES"] }
install_crate = { crate_name = "taplo-cli", binary = "taplo", test_arg = [
  "--help",
] }
command = "taplo"
args = ["format", "${CARGO_MAKE_FORMAT_TOML_FILES}", "--check"]

[tasks.clippy]
env = { CARGO_MAKE_CLIPPY_ARGS = "-- -D warnings" }
