[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
CARGO_MAKE_WORKSPACE_EMULATION = true
CARGO_MAKE_CRATE_WORKSPACE_MEMBERS = ["dsp", "control", "benches"]

[tasks.dev]
workspace = false
dependencies = ["format-black", "format-toml"]
run_task = { name = "dev-workspace", fork = true }

[tasks.dev-workspace]
dependencies = ["format", "clippy", "build", "test"]

[tasks.ci]
workspace = false
dependencies = ["print-env-flow", "check-black", "check-toml"]
run_task = { name = "ci-workspace", fork = true }

[tasks.ci-workspace]
dependencies = ["check-format", "clippy", "build", "test"]

[tasks.test]
condition = { files_not_exist = [".cargo"] }

[tasks.check-toml]
env = { CARGO_MAKE_FORMAT_TOML_ARGS = "--check" }
run_task = { name = "format-toml" }

[tasks.clippy]
env = { CARGO_MAKE_CLIPPY_ARGS = "--tests --benches -- -Dclippy::all -Dclippy::pedantic" }

[tasks.format-black]
condition_script = ["python3 -m black --help >/dev/null"]
condition = { fail_message = "Python black is not available" }
script = "python3 -m black hack/"

[tasks.check-black]
script = "python3 -m black hack/"
