[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
CARGO_MAKE_WORKSPACE_EMULATION = true
CARGO_MAKE_CRATE_WORKSPACE_MEMBERS = ["dsp", "control", "benches", "firmware"]

[tasks.default]
alias = "dev"

[tasks.dev]
workspace = false
dependencies = ["format-black", "format-toml"]
run_task = { name = "dev-workspace", fork = true }

[tasks.dev-workspace]
dependencies = ["format", "clippy", "build", "test"]

[tasks.ci]
workspace = false
dependencies = ["print-env-flow", "check-black", "check-toml"]
run_task = { name = "ci-workspace", fork = true }

[tasks.ci-workspace]
dependencies = ["check-format", "clippy", "build", "test"]

[tasks.test]
condition = { files_not_exist = [".cargo/"] }

[tasks.check-toml]
env = { CARGO_MAKE_FORMAT_TOML_ARGS = "--check" }
run_task = { name = "format-toml" }

[tasks.clippy]
env = { CARGO_MAKE_CLIPPY_ARGS = "--tests --benches -- -Dclippy::all -Dwarnings" }

[tasks.format-black]
condition_script = ["python3 -m black --help >/dev/null"]
condition = { fail_message = "Python black is not available" }
script = "python3 -m black hack/"

[tasks.check-black]
script = "python3 -m black hack/"

[tasks.manual]
workspace = false
script = "make -C manual/user && make -C manual/build"

[tasks.flash]
workspace = false
script = '''
cd firmware
cargo run --release --bin firmware --features idle-measuring
'''

[tasks.flash-dfu]
workspace = false
script = '''
cd firmware
cargo objcopy --release -- -O binary target/kaseta.bin
dfu-util -a 0 -s 0x08000000:leave -D target/kaseta.bin -d ,0483:df11
'''

[tasks.bench]
clear = true
workspace = false
script = '''
cd benches
cargo run --release --bin ${1}
'''

[tasks.test-embedded]
clear = true
workspace = false
script = '''
cd firmware
DEFMT_LOG=info cargo test --test ${1}
'''

[tasks.bloat]
workspace = false
script = '''
cd firmware
cargo size --bin firmware --release -- -m
cargo bloat --release
'''
